### ISSUE TITLE
update for psi4 Dimension update

### ISSUE THREAD

**Issue by loriab** [psi4/psi4pasture#4]
If you have time, @amjames, do you want to update the pasture plugins for the psi4/psi4#574 Dimension class modernization? Will probably just be a few changes like [these](https://github.com/psi4/psi4/pull/576/commits/46dee75fc18cfdc95da4faa24b10f3b4523c4ddd) in the CheMPS2 interface.

**Comment by amjames** [comment]
I have a few things that need my immediate attention, but I should be able to get to this in a couple of days.  If it can wait, I can have it done by this weekend at the latest.

**Comment by loriab** [comment]
Sure, no hurry. I just realized that the Dimension business hadn't propagated.
